image: python:3.9.7

stages:
  - documentation
  - release


documentation:
  image: registry.gitlab.com/markuspichler/swmm_api
  stage: documentation
  script:
  - cp README.md ./documentation/README.md
  - cp CHANGELOG.md ./documentation/CHANGELOG.md
  - sphinx-build -b html ./documentation public
  artifacts:
    paths:
    - public
  only:
    refs:
    - main


# https://github.com/python-semantic-release/python-semantic-release
# https://python-semantic-release.readthedocs.io/en/latest/
release-package-python:
  image: registry.gitlab.com/markuspichler/swmm_api
  stage: release
  script:
    - git config --global user.email "gitlab-ci@python-semantic-release.com"
    - git config --global user.name "python-semantic-release"
    - semantic-release publish -v DEBUG
  only:
    refs:
      - main
