image: registry.gitlab.com/markuspichler/swmm_api

pages:
  stage: deploy
  script:
  - cp README.md ./documentation/README.md
  - cp CHANGES.md ./documentation/CHANGES.md
  - sphinx-build -b html ./documentation public
  artifacts:
    paths:
    - public
  only:
  - master
