plugins:
  - "@semantic-release/commit-analyzer"
#  - - "@google/semantic-release-replace-plugin"
#    - replacements:
#        - files:
#            - py_ewa/__init__.py
#          from: __VERSION__ = ".*"
#          to: __VERSION__ = "${nextRelease.version}"
#          results:
#            - file: py_ewa/__init__.py
#              hasChanged: true
#              numMatches: 1
#              numReplacements: 1
#          countMatches: true
#  - - "@semantic-release/gitlab"
#    - gitlabUrl: https://gitlab.tugraz.at
#      assets:
#      - py_ewa/__init__.py
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo VERSION=${nextRelease.version} > build.env"
#  - - "@semantic-release/changelog"
#    - changelogFile: CHANGELOG.md
#  - - "@semantic-release/gitlab"
#    - gitlabUrl: https://gitlab.tugraz.at
#      assets:
#      - CHANGELOG.md
branches:
  - "main"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "alpha"
    prerelease: "alpha"
